# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzsource',
            name='last_refresh_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 19, 14, 24, 48, 325495)),
        ),
    ]
