# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20170219_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzsource',
            name='last_refresh_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
