# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20170219_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzsource',
            name='last_refresh_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
